server.port=8091
spring.application.name=auth-service

# Must be 32+ chars for HS256 key material
auth.jwt.secret=${AUTH_JWT_SECRET:investai-super-secret-key-change-me-2026}
auth.jwt.access-ttl-seconds=900
auth.jwt.refresh-ttl-seconds=604800

#spring.datasource.url=${AUTH_DB_URL:jdbc:postgresql://localhost:5432/investai_auth}
spring.datasource.url=${AUTH_DB_URL:jdbc:postgresql://localhost:5450/postgres}
spring.datasource.username=${AUTH_DB_USERNAME:postgres}
spring.datasource.password=${AUTH_DB_PASSWORD:root1234}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_schema=invest_platform_ai
