server.port=8082
spring.application.name=portfolio-service

spring.datasource.url=${PORTFOLIO_DB_URL:jdbc:postgresql://localhost:5432/investai_auth}
spring.datasource.username=${PORTFOLIO_DB_USERNAME:investai}
spring.datasource.password=${PORTFOLIO_DB_PASSWORD:investai}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=invest_platform_ai
